version: 2
updates:
  - package-ecosystem: github-actions
    open-pull-requests-limit: 10
    directory: /
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
    schedule:
      interval: daily
      time: "10:00"
      timezone: America/Toronto
