# ----------------------------------------------- #
# Note: this file originates in template-template #
# ----------------------------------------------- #

name: pull_request_target

on: pull_request_target

permissions: read-all

jobs:
  main:
    uses: ahmadnassri/actions/.github/workflows/pull-request-target-template.yml@master
    secrets:
      github-token: ${{ secrets.GH_TOKEN }}
    permissions:
      contents: write
      pull-requests: write
